### ISSUE TITLE
Failed to create symbolic link

### ISSUE THREAD

**Issue by Mavrick91** [ngryman/lol-items#7]
Hey, i struggle to install this dependency, i got an error:
`ln: failed to create symbolic link 'node_modules/lol-items': No such file or directory`.
But i succeeded to install the others dependency `lol-champions` and `lol-spells`

Does someone has the same issue ?

**Comment by ngryman** [comment]
@Mavrick91 Could you try with the latest version (`lol-items@7.8.1`)? Thanks!
